{% set version = "0.16.1" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  fn: mkdocs-{{ version }}.tar.gz
  url: https://github.com/mkdocs/mkdocs/archive/{{ version }}.tar.gz
  sha256: b665679d7c6da47e734a00e89f823e478cc57389ffeb49266de68a804f803f83

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click >=3.3
    - jinja2 >=2.7.1
    - livereload >=2.3.2
    - markdown >=2.3.1
    - mkdocs-bootstrap >=0.1.1
    - mkdocs-bootswatch >=0.1.0
    - pyyaml >=3.10
    - tornado >=4.1

test:
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  summary: 'Project documentation with Markdown.'

extra:
  recipe-maintainers:
    - ocefpaf
