{% set version = "0.17.1" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: c6f1c5d71fe6e92b66a447fd2713afcb006f148c45c468a8f926c6b5b2c4d094

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click >=3.3
    - jinja2 >=2.7.1
    - livereload >=2.5.1
    - markdown >=2.3.1
    - pyyaml >=3.10
    - tornado >=4.1

test:
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Project documentation with Markdown.'

extra:
  recipe-maintainers:
    - ocefpaf
