{% set version = "1.1" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: 9243291392f59e20b655e4e46210233453faf97787c2cf72176510e868143174

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click >=3.3
    - jinja2 >=2.7.1
    - livereload >=2.5.1
    - markdown >=2.3.1
    - pyyaml >=3.10
    - tornado >=5.0

test:
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Project documentation with Markdown.'

extra:
  recipe-maintainers:
    - ocefpaf
