{% set version = "1.1.2" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: f0b61e5402b99d7789efa032c7a74c90a20220a9c81749da06dbfbcbd52ffb39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - click >=3.3
    - jinja2 >=2.10.1
    - livereload >=2.5.1
    - lunr ==0.5.8
    # lunr[languages]
    - nltk >=3.2.5
    - markdown >=3.2.1
    - pyyaml >=3.10
    - tornado >=5.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.contrib
    - mkdocs.contrib.search
    - mkdocs.structure
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.structure
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Project documentation with Markdown'

extra:
  recipe-maintainers:
    - ocefpaf
