travis:
  secure:
    BINSTAR_TOKEN: etHtSZj/l4l/BqJmkgRZ+mvQaCLIZzDxnoTD2HaXLqWDcZJnjb9/VPAEQLdIR+pxSICIae4OBcwy3IS0CGGQW+ZNtqUzYK3APppUwygCvz7aWZB6fd0PVPFxgOFdnlcTHfR7SqhAOr11o0IASQA+1YHetywFrllJ4HJCD8obFtBH4woM90gQqvhAOn27zenzUK4vSyzQB6yrrri4t2dEfb3VI5f7rJN6hoZ2/fPkfQdw7NLp9KAgfGxgytSYT6I7mr8i2W6knBmxmB54BYiwjoYN1D1sqBL6dumdNIkloFLcLbH1Locn5Kk32yo28IXXwEm/q/8pMH7WS3cDG5aNlxPdII+aUEPBGQuKmRZrPMr60uURUJzNMJ+BcKg7DGKgjN1fjmUs34tRkPScyCTPB4HDeMbqtSkEyGiFZklV4s7JpzMH7Y4Bcz8WEPVtSOuhlQP5Q8hCXaYmOlviPx8hEOkegSOTSNlAOBVWtTqaMWYedsTxtJXi308e5BDPsBKOwW21BEijA05/N6bh4xLReH8ahCKQI7hrqwmqhz+hj8++C/OeP/SNPPIUI7HISQetz1qBm/dku84OthovjtjRXAacA7tBuOOORPCMoCMLKZ62u7tySDEvLC+qZFZi8kEmnWt2OOLlaaVDePUXOEcEWh1MBUXzWwIlk/Kzjo7xceU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
