travis:
  secure:
    BINSTAR_TOKEN: RDt29VydOtmmSaI3EXB/TBI106Q1xovsRh4dWdRCrqVLDPBbXVmkEEuymhPYZwlSR6cKUUb9I1QpxmMeH6dhambI6uw7pLKbFbwUqN4mXrVuuXqlUrlFMw7PPnYObaMUUI+aiL1Iy74/2/yIYUvzmq2+Wo9JyZYJ+F3TsuJaFgECikWQzm3miC71mFR+F6OH85AVDUMvWrnL6RyktF1bgOyGnrnM1ot//FfzXN4gtf1R1lb762VFz4J/yDgS7GufCNpYDIyKDaNV9STENjEJJYFmV+aj950L5w594b72HEn6bJYKlLGh02zx0kDNjhe5f1XYGolfYDINPWlec6d8nlp6jVEV/pIfZYJkSj8d4fJ8vWiPaa7/3uZmOZmaq76gGs2ET+MrXFKE2cIFSwlhVThL1OKVUzPYwF2RGL4chq4lZWuEdF0CaVvsFUeufooBtvfyavzCBbPtBsuMx+StIf0Wu5KKOsnE+CuyOMWaejQrZiXUjjynbZ54l91/vr5NH7+pA1Bghk1EbwXLiS/uyFem9yjV6xiV2pEgXIEjXsZ9x/Ye42R20afu+i4n0ZRveM5jbEvHvmRvRLBGvaT5Hfy0cvCFahKeK4MCaEeCGvEWFsdd/cYPSTTlaKcJ9yvqnbFZefh7wVQNAKc6jWP793bhe0iMQu3/qrAjgIfohYw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
